"""create exercises workouts sequences sets

Revision ID: 077a1da3f52a
Revises: c18404816173
Create Date: 2026-06-04 18:40:54.169131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '077a1da3f52a'
down_revision: Union[str, None] = 'c18404816173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('muscle_groups', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('equipment_required', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('movement_patterns', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_reps', sa.Boolean(), nullable=False),
    sa.Column('is_duration', sa.Boolean(), nullable=False),
    sa.Column('supports_weight', sa.Boolean(), nullable=False),
    sa.Column('is_bilateral', sa.Boolean(), nullable=False),
    sa.Column('bilateral_pair_id', sa.UUID(), nullable=True),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('workout_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('WARMUP', 'MAIN', 'COOLDOWN', name='workoutphase'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_type', sa.Enum('STRENGTH', 'CARDIO', name='settype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['workout_sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('workout_sequences')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    sa.Enum(name='settype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workoutphase').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
